# Rule Configuration
rules:
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 2
  mixins-before-declarations:
    - 2
    -
      exclude:
        - breakpoint
        - mq

  no-warn: 1
  no-debug: 1
  no-ids: 2
  no-important: 0
  hex-notation:
    - 2
    -
      style: lowercase
  indentation:
    - 2
    -
      size: 4
  property-sort-order:
    - 1
    -
      order: concentric
      ignore-custom-properties: true
  variable-for-property:
    - 0

  clean-import-paths:
    - 1
    -
      leading-underscore: true
      filename-extension: true
  nesting-depth:
    - 1
    -
      max-depth: 4
  force-pseudo-nesting: 0
  no-color-literals: 0
  force-element-nesting: 0
  quotes:
    - 1
    -
      style: double
